
import type { Metadata } from "next";
import "../globals.css";
import React, {ReactNode} from "react";
import {ThemeProvider} from "../../component/material";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: ReactNode;

}>) {
    return (
        <>
        {children}
        </>
    );
}
